name: CMake Build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake make g++ libyaml-cpp-dev libboost-all-dev

      - name: Create build directory
        run: mkdir build

      - name: Run CMake
        run: cmake ..
        working-directory: build

      - name: Build project
        run: make -j
        working-directory: build
