name: CMake Build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake make g++ libyaml-cpp-dev libboost-all-dev

      - name: Check cmake version
        run: cmake --version

      - name: Check make version
        run: make --version

      - name: Download Tar.gz file
        run: wget -O source.tar.gz "https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.gz"

      - name: Create eigen3 directory
        run: mkdir eigen3

      - name: Extract Tar.gz file
        run: tar -xzvf source.tar.gz -C eigen3

      - name: Check pwd
        run: pwd

      - name: Create build directory
        run: mkdir build

      - name: Run CMake
        run: cmake -DEIGEN3_INCLUDE_DIR=/home/runner/work/testing-boost-exercise/testing-boost-exercise/eigen3 ..
        working-directory: build

      - name: Build project
        run: make -j
        working-directory: build
